"""Generate the frontend WebSocket protocol constants from app/ws/schemas.py.

WebSocket messages are not in the OpenAPI document, so without this the frontend would keep its own copy of the type and status strings.
The generated file is committed and tests/test_units.py fails if it is stale.

Regenerate with: uv run python scripts/gen_ws_contract.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.settings import ROOT
from app.ws.schemas import JOB_STATUSES, MESSAGE_TYPES

OUT = ROOT / "frontend" / "src" / "api" / "ws-contract.generated.js"

HEADER = """// Generated by scripts/gen_ws_contract.py from app/ws/schemas.py.
// Do not edit by hand.
// Regenerate with: uv run python scripts/gen_ws_contract.py
"""


def _const_block(name: str, values: tuple[str, ...]) -> str:
    entries = "\n".join(f"  {v.upper()}: '{v}'," for v in values)
    return f"export const {name} = Object.freeze({{\n{entries}\n}})\n"


def _list_block(name: str, values: tuple[str, ...]) -> str:
    entries = ", ".join(f"'{v}'" for v in values)
    return f"export const {name} = Object.freeze([{entries}])\n"


def render() -> str:
    return "\n".join(
        [
            HEADER,
            _const_block("MESSAGE_TYPE", MESSAGE_TYPES),
            _const_block("JOB_STATUS", JOB_STATUSES),
            "// The frontend job handler table must cover every status here (see stores/run.js).",
            _list_block("JOB_STATUSES", JOB_STATUSES),
        ]
    )


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
